import type { Metadata } from "next";
import "../app/globals.css";
import Header from "../components/ui/Header";
import Footer from "../components/ui/Footer";

export const metadata: Metadata = {
  title: "Museu Tecnológico",
  description: "Generated by create next app",
};

const SetInitialTheme = () => (
  <script
    dangerouslySetInnerHTML={{
      __html: `(function(){try{var s=localStorage.getItem('theme');var p=window.matchMedia('(prefers-color-scheme: dark)').matches;var d=s?s==='dark':p;document.documentElement.classList.toggle('dark',d);}catch(e){}})();`,
    }}
  />
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <head>
        <SetInitialTheme />
      </head>
      <body className="flex flex-col min-h-screen bg-white text-gray-900 dark:bg-gray-950 dark:text-gray-100">
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
